import Head from "next/head";
import Nav from "../../components/Nav";
import Image from "next/image";
import contactbg from "../../assests/contactbg.jpg";
import CallIcon from "@mui/icons-material/Call";
import LocationOnIcon from "@mui/icons-material/LocationOn";
import EmailIcon from "@mui/icons-material/Email";
import Footer from "../../components/Footer";
import { FormEvent, useState } from "react";
import React, { useRef } from 'react';
import emailjs from '@emailjs/browser';


type Props = {};
function Contact({}: Props) {
  const [name, setName] = useState<string>();
  const [email, setEmail] = useState<string>();
  const [phone, setPhone] = useState<string>();
  const [subject, setSubject] = useState<string>();
  const [message, setMessage] = useState<string>();

  console.log(name,email, phone, subject, message);

const form = useRef<HTMLFormElement>(null);
  function sendEmail(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const currentForm = form.current;

    if (currentForm == null) {
      return;
    }
    else {
      emailjs.sendForm("service_spab4la" , "template_3gs2ipj", form.current! ,'5lDQ2fsinXAaz-OgN').then((result) => {
        console.log(result.text);
      },(error) => {
        console.log(error.message);
      }
      ) 

    }


  }

  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main>
        <Nav />
        <div className=" relative">
          <Image
            src={contactbg}
            alt="contact page backgroudn image"
            width={1920}
            height={1080}
            className="  md:h-[300px] object-cover object-center brightness-50"
          />
          <h1 className="text-white font-bold text-2xl md:text-4xl absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
            Contact{" "}
          </h1>
        </div>
        <div className="p-4 space-y-4 flex flex-col items-center md:space-y-0 md:flex-row md:space-x-8 md:p-8 md:justify-center ">
          <div className="flex flex-col items-center  space-y-2 justify-center hover:border-black rounded-lg border w-[300px] h-[250px] ">
            <CallIcon
              className=" bg-[#4a686a] text-white p-2 rounded-full "
              style={{ fontSize: "50" }}
            />
            <h2 className="text-gray-800 font-bold">Dial and Get Solution:</h2>
            <h3 className="text-gray-600">02333232432</h3>
          </div>
          <div className="flex flex-col items-center space-y-2 justify-center hover:border-black rounded-lg border w-[300px] h-[250px] ">
            <LocationOnIcon
              className=" bg-[#4a686a] text-white p-2 rounded-full "
              style={{ fontSize: "50" }}
            />
            <h2 className="text-gray-800 font-bold">Find Our Office:</h2>
            <h3 className="text-gray-600">6th Floor, Barbosa Sydney</h3>
          </div>
          <div className="flex flex-col items-center space-y-2 justify-center hover:border-black rounded-lg border w-[300px] h-[250px]">
            <EmailIcon
              className=" bg-[#4a686a] text-white p-2 rounded-full "
              style={{ fontSize: "50" }}
            />
            <h2 className="text-gray-800 font-bold">Mail us Anytime:</h2>
            <h3 className="text-gray-600">info@sparkandclean.com.au</h3>
          </div>
        </div>

        <div className="mt-10 flex flex-col items-center">
          <h1 className="text-2xl md:text-3xl font-bold text-gray-800 text-center">
            Get In Touch
          </h1>

          <form ref={form}  onSubmit={sendEmail} className=" md:max-w-[600px] max-w-[400px] mt-10 space-y-4 md:flex md:flex-wrap md:space-y-0  ">
            <div className="space-y-2 w-[300px] p-2">

            <div className="flex flex-col ">
              <label>Name</label>
              <input
              onChange={(e) => setName(e.target.value)} 
                type="text"
                required
                name="user_name"
                className="bg-gray-200 text-sm p-2  outline-none rounded-lg "
              ></input>
            </div>
            <div className="flex flex-col ">
              <label>Email</label>
              <input
                type="text"
                onChange={(e) => setEmail(e.target.value)} 
                required
                name="user_email"
                className="bg-gray-200 text-sm p-2 outline-none rounded-lg "
              ></input>
            </div>
            </div>

            <div className="space-y-2 w-[300px] p-2">


            <div className="flex flex-col ">
              <label>Phone</label>
              <input
              onChange={(e) => setPhone(e.target.value)}
                type="text"
                name="phone_number"
                required
                className="bg-gray-200 text-sm p-2 outline-none rounded-lg "
              ></input>
            </div>
            <div className="flex flex-col ">
              <label>Subject</label>
              <input
                type="text"
                onChange={(e) =>  setSubject(e.target.value)}
                required
                name="subject"
                className="bg-gray-200 text-sm p-2 outline-none rounded-lg "
              ></input>
            </div>
            </div>
            <div className="flex flex-col md:w-[600px] ">
              
              <label>Message</label>
              <textarea name="message"  onChange={(e) => setMessage(e.target.value)} className="bg-gray-200 text-sm outline-none  h-[200px] p-2 rounded-lg"></textarea>
            </div>
            <button type="submit" className="bg-red  text-white px-3 py-1 rounded-lg"> Send </button>
          </form>
        </div>
      </main>
      <Footer />
    </>
  );
}
export default Contact;
